// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_IVTRmopblO3zLauu-W4m5jClnCSgsx0',
    appId: '1:290688715852:web:959e64b0b0b79490f578e9',
    messagingSenderId: '290688715852',
    projectId: 'news-app-aab35',
    authDomain: 'news-app-aab35.firebaseapp.com',
    storageBucket: 'news-app-aab35.appspot.com',
    measurementId: 'G-K1S4NCBK2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPnatySSkNBxnRKxGTpswlYtM5v6KceDE',
    appId: '1:290688715852:android:cf82c0bf0809b358f578e9',
    messagingSenderId: '290688715852',
    projectId: 'news-app-aab35',
    storageBucket: 'news-app-aab35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRRCRndV-K-CmeN_KGLZh4yPyIvqvZYXQ',
    appId: '1:290688715852:ios:fa78eb8a678cb0b1f578e9',
    messagingSenderId: '290688715852',
    projectId: 'news-app-aab35',
    storageBucket: 'news-app-aab35.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
